/**
 * Test setup and configuration
 * Generated by Claude Testing Infrastructure
 */



// Global test setup

beforeAll(() => {
  // Global setup before all tests
});

afterAll(() => {
  // Global cleanup after all tests
});

beforeEach(() => {
  // Setup before each test
});

afterEach(() => {
  // Cleanup after each test
});


// Mock console methods to reduce noise in tests
global.console = {
  ...console,
  warn: jest.fn(),
  error: jest.fn(),
};

// React testing configuration
// Import jest-dom for additional matchers
// Note: This assumes @testing-library/jest-dom is installed
try {
  require('@testing-library/jest-dom');
} catch (e) {
  // @testing-library/jest-dom not available - using basic matchers
}

// Mock window.matchMedia for responsive components (only in browser environments)
if (typeof window !== 'undefined') {
  Object.defineProperty(window, 'matchMedia', {
    writable: true,
    value: jest.fn().mockImplementation(query => ({
      matches: false,
      media: query,
      onchange: null,
      addListener: jest.fn(), // deprecated
      removeListener: jest.fn(), // deprecated
      addEventListener: jest.fn(),
      removeEventListener: jest.fn(),
      dispatchEvent: jest.fn(),
    })),
  });
}
